#!/bin/sh
set -e              # exit on any command failure

npm-link-check      # ensure we haven't been testing against npm link'd modules
npm run lint        # 
npm run prettier    # 
npm run test        #
